# Generated by Django 5.1.1 on 2025-05-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="tracking_number",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
