# Generated by Django 5.1.1 on 2025-05-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0002_alter_package_tracking_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("NGN", "Nigerian Naira"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                ],
                default="USD",
                help_text="Currency for total worth and clearance fee",
                max_length=3,
            ),
        ),
    ]
