# Generated by Django 5.1.1 on 2025-05-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0003_package_currency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="package",
            name="currency",
        ),
        migrations.AddField(
            model_name="package",
            name="clearance_fee_currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("NGN", "Naira"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="total_worth_currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("NGN", "Naira"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("awaiting_clearance", "Awaiting Clearance"),
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
