# Generated by Django 5.2.1 on 2025-05-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0004_remove_package_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="clearance_fee_currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("ZAR", "Rand"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="total_worth_currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("ZAR", "Rand"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
    ]
